#!/usr/bin/env python3
"""
build_holds_surface.py
======================

Regenerate the holds surface: one line per open resume record, collected from
every plan in the vault and written to `<logs>/Holds.md`.

Why this exists
---------------
A hold escalates onto its plan as a resume record — `- [ ] HOLD (YYYY-MM-DD) —
<forward-looking prompt>` (CONFIG § Holds and approvals) — and the queue line
clears, so the plan entry becomes the only live copy. That is the right home for
the decision, but a decision resting in one plan among dozens is invisible until
someone opens that plan. This surface is the index over them: generated, never
hand-edited, so no second authority exists to drift from the plans themselves.

It follows `build_state_index`'s contract deliberately: one shared file,
overwritten whole each run, carrying a do-not-edit banner. A record is closed by
checking its line **on the plan**; the next regeneration drops it from here.

Read by the action-agent each pass and by the session brief on engagement.

Usage
-----
    JANITOR_VAULT_ROOT=<vault> python build_holds_surface.py [--check]

`--check` prints the records and writes nothing (exit 0 always; this is a
reporting surface, not a gate).
"""
from __future__ import annotations

import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(_SCRIPTS_DIR))

from config_variables import (  # noqa: E402
    _folder_by_semantic,
    is_excluded_dir,
    token_path,
)

# `- [ ] HOLD (2026-07-26) — prompt`, tolerating `*` bullets, an em- or plain
# dash, and any spacing. A checked box is a closed record and never collected.
_HOLD_RE = re.compile(
    r"^\s*[-*]\s+\[\s\]\s+HOLD\s*\((\d{4}-\d{2}-\d{2})\)\s*[—-]\s*(.+?)\s*$"
)


def collect_holds(vault_root: Path) -> list[dict]:
    """Return every open resume record in the vault, newest date first."""
    records: list[dict] = []
    for dirpath, dirnames, filenames in os.walk(vault_root):
        dirnames[:] = [d for d in dirnames if not is_excluded_dir(d) and not d.startswith(".")]
        for fname in filenames:
            if not fname.endswith(".md"):
                continue
            path = Path(dirpath) / fname
            rel = path.relative_to(vault_root).as_posix()
            # The archive holds superseded copies; a retired plan's hold is not live.
            if rel.startswith(_folder_by_semantic("archive") + "/"):
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if "HOLD (" not in text:
                continue
            for lineno, line in enumerate(text.splitlines(), 1):
                m = _HOLD_RE.match(line)
                if m:
                    records.append({
                        "date": m.group(1),
                        "prompt": m.group(2).strip(),
                        "plan": rel,
                        "stem": path.stem,
                        "line": lineno,
                    })
    records.sort(key=lambda r: (r["date"], r["plan"]), reverse=True)
    return records


def render(records: list[dict], now: str) -> str:
    out = [
        "<!-- GENERATED by build_holds_surface.py — do not edit. A record is closed by",
        "     checking its line on the owning plan; the next run drops it from here. -->",
        "",
        "# Holds",
        "",
        "Open resume records — decisions escalated off the queue and now resting on a",
        "plan, each written as the opening move of the session that picks it up.",
        "",
        f"_Regenerated {now} — {len(records)} open._",
        "",
    ]
    if not records:
        out += ["No open holds.", ""]
        return "\n".join(out)
    out += ["| raised | resume prompt | plan |", "| ------ | ------------- | ---- |"]
    for r in records:
        prompt = r["prompt"].replace("|", "\\|")
        out.append(f"| {r['date']} | {prompt} | [[{r['stem']}]] |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    check = "--check" in sys.argv
    root = os.environ.get("JANITOR_VAULT_ROOT")
    if not root:
        print("JANITOR_VAULT_ROOT not set", file=sys.stderr)
        return 2
    vault_root = Path(root).resolve()
    records = collect_holds(vault_root)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ")

    if check:
        print(f"{len(records)} open hold(s)")
        for r in records:
            print(f"  {r['date']}  {r['plan']}:{r['line']}  {r['prompt'][:90]}")
        return 0

    dest = vault_root / token_path("logs", "Archive/Logs") / "Holds.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(render(records, now), encoding="utf-8")
    print(f"Holds.md written: {dest}")
    print(f"  {len(records)} open record(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
